-- Migration 036: first-class backlog items
--
-- backlog_items becomes the user-facing backlog source of truth. It can be
-- created manually without a requirement, or linked to planning/candidate
-- artifacts when generated by the system.

CREATE TABLE IF NOT EXISTS backlog_items (
    id TEXT PRIMARY KEY,
    project_id TEXT NOT NULL,
    requirement_id TEXT,
    planning_run_id TEXT,
    backlog_candidate_id TEXT,
    task_id TEXT,
    title TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    status TEXT NOT NULL DEFAULT 'triage',
    priority TEXT NOT NULL DEFAULT 'medium',
    source TEXT NOT NULL DEFAULT 'human',
    rank INTEGER NOT NULL DEFAULT 0,
    labels JSONB NOT NULL DEFAULT '[]',
    acceptance_criteria TEXT NOT NULL DEFAULT '',
    blocked_reason TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
    FOREIGN KEY (requirement_id) REFERENCES requirements(id) ON DELETE SET NULL,
    FOREIGN KEY (planning_run_id) REFERENCES planning_runs(id) ON DELETE SET NULL,
    FOREIGN KEY (backlog_candidate_id) REFERENCES backlog_candidates(id) ON DELETE SET NULL,
    FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_backlog_items_project_status_rank
    ON backlog_items(project_id, status, rank ASC, updated_at DESC);

CREATE INDEX IF NOT EXISTS idx_backlog_items_project_priority
    ON backlog_items(project_id, priority);

CREATE INDEX IF NOT EXISTS idx_backlog_items_project_updated
    ON backlog_items(project_id, updated_at DESC);

CREATE UNIQUE INDEX IF NOT EXISTS idx_backlog_items_candidate_unique
    ON backlog_items(backlog_candidate_id)
    WHERE backlog_candidate_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_backlog_items_task_unique
    ON backlog_items(task_id)
    WHERE task_id IS NOT NULL;

ALTER TABLE task_lineage
    ADD COLUMN backlog_item_id TEXT REFERENCES backlog_items(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_task_lineage_backlog_item_id
    ON task_lineage(backlog_item_id);
