// Package wire — context.v2 wire contract additions.
//
// PlanningContextV2 is an envelope that wraps a V1 context with role,
// intent-mode, task-scale, and pack-ID metadata. It is used by the
// planning-context snapshot store (Phase 3B) to record a richer audit trail
// without breaking the V1 contract delivered to connectors.
//
// This file is intentionally a leaf: no imports outside the standard library.
package wire

import "time"

// ContextSchemaV2 is the schema version string embedded in every V2 payload.
const ContextSchemaV2 = "context.v2"

// IntentMode captures the high-level intent of the planning run.
type IntentMode string

const (
	IntentModeAnalyze   IntentMode = "analyze"
	IntentModeImplement IntentMode = "implement"
	IntentModeReview    IntentMode = "review"
	IntentModeDocument  IntentMode = "document"
)

// TaskScale is a coarse estimate of task complexity, used to gate context
// budget allocation in future phases.
type TaskScale string

const (
	TaskScaleSmall  TaskScale = "small"
	TaskScaleMedium TaskScale = "medium"
	TaskScaleLarge  TaskScale = "large"
)

// SourceRef describes one file or document that served as a source of truth
// for the planning run. Role is a human-readable label such as "safety-rules"
// or "architecture-decision".
type SourceRef struct {
	Name string `json:"name"`
	Path string `json:"path"`
	Role string `json:"role"`
}

// PlanningContextV2 is the V2 planning wire context. It reuses V1 nested
// types (PlanningContextLimits, PlanningContextSources, PlanningContextMeta)
// and adds envelope metadata for role, intent, scale, and provenance.
//
// Wire contract rules:
//   - SchemaVersion is always ContextSchemaV2.
//   - PackID is a UUID v4 string generated by the server at run-creation time.
//   - SourceOfTruth is non-nil after construction (may be empty slice).
//   - Adding new fields is non-breaking; renaming requires a new schema version.
type PlanningContextV2 struct {
	SchemaVersion    string                 `json:"schema_version"` // "context.v2"
	PackID           string                 `json:"pack_id"`        // UUID
	Role             string                 `json:"role"`           // e.g. "backend-architect"
	IntentMode       IntentMode             `json:"intent_mode"`    // analyze|implement|review|document
	TaskScale        TaskScale              `json:"task_scale"`     // small|medium|large
	GeneratedAt      time.Time              `json:"generated_at"`
	GeneratedBy      string                 `json:"generated_by"`
	SanitizerVersion string                 `json:"sanitizer_version"`
	Limits           PlanningContextLimits  `json:"limits"`
	SourceOfTruth    []SourceRef            `json:"source_of_truth"`
	Sources          PlanningContextSources `json:"sources"`
	Meta             PlanningContextMeta    `json:"meta"`
}

// UpgradeV1ToV2 wraps a V1 context with V2 envelope fields.
// The V1 sources, limits, and meta are copied verbatim; only the outer
// schema version and the new fields differ.
//
// packID, role, intentMode, taskScale, and sourceOfTruth come from the
// caller. SourceOfTruth is normalized to an empty non-nil slice when nil is
// passed so JSON serialization always produces "source_of_truth": [].
func UpgradeV1ToV2(v1 PlanningContextV1, packID, role string, intentMode IntentMode, taskScale TaskScale, sourceOfTruth []SourceRef) PlanningContextV2 {
	sot := sourceOfTruth
	if sot == nil {
		sot = []SourceRef{}
	}
	return PlanningContextV2{
		SchemaVersion:    ContextSchemaV2,
		PackID:           packID,
		Role:             role,
		IntentMode:       intentMode,
		TaskScale:        taskScale,
		GeneratedAt:      v1.GeneratedAt,
		GeneratedBy:      v1.GeneratedBy,
		SanitizerVersion: v1.SanitizerVersion,
		Limits:           v1.Limits,
		SourceOfTruth:    sot,
		Sources:          v1.Sources,
		Meta:             v1.Meta,
	}
}
